[package]
name = "aura"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "aura"
test = false
bench = false

[dependencies]
cortex-m = "0.7"
cortex-m-rt = { version = "0.7", features = ["device"] }
panic-halt = "0.2"
kd32f328-pac = { path = "../kd32f328-pac", features = ["rt"] }
embedded-hal = "1.0"
embedded-hal-bus = "0.3"
display-interface = "0.5"
display-interface-spi = "0.5"
st7565 = "0.6"
embedded-graphics = "0.8"
profont = "0.7"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
debug = true
panic = "abort"

[profile.dev]
opt-level = "z"
panic = "abort"
lto = true
codegen-units = 1
